WITH RECURSIVE CTE(DEPT_ID, DEPT_NAME, UP_DEPT_ID)
AS (
	SELECT DEPT_ID, DEPT_NAME, UP_DEPT_ID
    FROM department
    WHERE UP_DEPT_ID IS NULL
    UNION ALL
    SELECT a.DEPT_ID, a.DEPT_NAME, a.UP_DEPT_ID
    FROM department a
    JOIN CTE b
    ON a.UP_DEPT_ID = b.DEPT_ID
)

SELECT DEPT_ID, DEPT_NAME, UP_DEPT_ID
FROM CTE;