CREATE TABLE DEPARTMENT (
	DEPT_ID INT PRIMARY KEY AUTO_INCREMENT,
    	DEPT_NAME VARCHAR(20) NOT NULL,
   	UP_DEPT_ID INT,
    	CONSTRAINT FK_UP_DEPT_ID FOREIGN KEY (UP_DEPT_ID) REFERENCES department (DEPT_ID)
);
